require 'rake/testtask'
require 'yard'
require 'fileutils'

require './lib/ansa/constants'
require './lib/ansa/docs/versions'


Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/test_ansa.rb'
end

YARD::Rake::YardocTask.new do |t|
  dynamic_dir = File.join('lib', 'ansa', 'docs')
  dynamic_file = File.join('lib', 'ansa', 'docs', 'dynamic_docs.rb')
  FileUtils.mkdir_p dynamic_dir
  f = File.new(dynamic_file, 'w')
  f.write("module Ansa")
  Ansa::LINKS.each do |key, value|
    f.write("\n  generate_get_news '#{key}', '#{value}', '#{AUTOGENERATED_METHODS_VERSIONS[key]}'")
  end
  f.write("\nend")
  t.files = ['lib/**/*.rb']
  t.stats_options = ['--list-undoc']
end

desc "Run tests"
task :default => :test
