require 'net/http'
require 'rss'
require "ansa/news"


module Ansa

  private
  def self.get_news_by_url(url)
    news = []
    rss = RSS::Parser.parse(open(url).read, false).items
    rss.each do |result|
      news.push(
        News.new(result.title, result.description, result.date, result.link)
      )
    end
    return news
  end

  # @!macro [attach] generate_get_news
  #   @method get_$1_news
  #   @!scope class
  #   @note This method is autogenerated, it fetches $2
  #   Get news for "$1" category.
  #   @since $3
  #   @return [Array<Ansa::News>] all the news of category "$1".
  def self.generate_get_news(category, value)
    define_singleton_method("get_#{category}_news") do
      get_news_by_url(value)
    end
  end

  public
  # Get news given a category.
  #
  # @param category name, `:text`
  # @since 1.0.0
  # @return [Array<Ansa::News>] all the news of the given category.
  def self.get_news(category)
    get_news_by_url(LINKS[category])
  end

  LINKS.each do |key, value|
    generate_get_news key, value
  end

end
