require 'ansa/constants'


AUTOGENERATED_METHODS_VERSIONS = {
  Ansa::HOMEPAGE => '1.0.0',
  Ansa::NEWS => '1.0.0',
  Ansa::POLITICS => '1.0.0',
  Ansa::WORLD => '1.0.0',
  Ansa::ECONOMY => '1.0.0',
  Ansa::SOCCER => '1.0.0',
  Ansa::SPORT => '1.0.0'
}
